Repository tenzir/threatbus, pull requests merged in 2020-05, with the labels that each got.

#26 Use direct link to docs
  README.md
Labels: enhancement :sparkles:

#28 Handle IoC removal in VAST bridge
  .gitignore
  apps/vast/vast-bridge.py
Labels: feature :gift:, maintenance :scissors:

#31 Bump all version numbers for May release
  plugins/apps/threatbus_misp/setup.py
  plugins/apps/threatbus_vast/setup.py
  plugins/apps/threatbus_zeek/setup.py
  plugins/backbones/threatbus_inmem/setup.py
  setup.py
Labels: maintenance :scissors:
