Repository tenzir/threatbus, pull requests merged in 2021-06, with the labels that each got.

#127 Simplify Slack URL
  README.md
Labels: maintenance :scissors:

#128 Fix forgotten URL in changelog
  CHANGELOG.md
Labels: maintenance :scissors:

#125 Report back Sightings from STIX-Shifter to Threat Bus
  apps/stix-shifter/CHANGELOG.md
  apps/stix-shifter/setup.py
  apps/stix-shifter/stix_shifter_threatbus/message_mapping.py
  apps/stix-shifter/stix_shifter_threatbus/shifter.py
  apps/stix-shifter/stix_shifter_threatbus/test_message_mapping.py
  apps/vast/setup.py
Labels: feature :gift:

#126 Add Dockerfiles for ZMQ Apps
  .github/workflows/python-egg.yml
  apps/stix-shifter/CHANGELOG.md
  apps/stix-shifter/Dockerfile
  apps/stix-shifter/README.md
  apps/vast/CHANGELOG.md
  apps/vast/Dockerfile
  apps/vast/README.md
Labels: feature :gift:

#129 Collect metrics about received but unprocessed IoCs in pyvast-threatbus
  apps/vast/CHANGELOG.md
  apps/vast/pyvast_threatbus/metrics.py
  apps/vast/pyvast_threatbus/pyvast_threatbus.py
Labels: feature :gift:

#130 Use point for URI indicators in pyvast-threatbus
  apps/vast/CHANGELOG.md
  apps/vast/pyvast_threatbus/message_mapping.py
  apps/vast/pyvast_threatbus/test_message_mapping.py
Labels: enhancement :sparkles:

#132 Update to Bullseye Docker-base & Debian-maintained Broker libs
  .github/workflows/python-egg.yml
  CHANGELOG.md
  Dockerfile
Labels: enhancement :sparkles:

#131 Implement Suricata App for ingesting rules from Threat Bus
  apps/suricata/CHANGELOG.md
  apps/suricata/Makefile
  apps/suricata/README.md
  apps/suricata/config.yaml.example
  apps/suricata/setup.py
  apps/suricata/suricata_threatbus/__init__.py
  apps/suricata/suricata_threatbus/suricata.py
Labels: feature :gift:

#134 June Release
  CHANGELOG.md
  apps/stix-shifter/CHANGELOG.md
  apps/stix-shifter/setup.py
  apps/suricata/CHANGELOG.md
  apps/suricata/setup.py
  apps/vast/CHANGELOG.md
  apps/vast/Dockerfile
  apps/vast/setup.py
  apps/zmq-app-template/setup.py
  plugins/apps/threatbus_cif3/setup.py
  plugins/apps/threatbus_misp/setup.py
  plugins/apps/threatbus_zeek/setup.py
  plugins/apps/threatbus_zmq_app/setup.py
  plugins/backbones/file_benchmark/setup.py
  plugins/backbones/threatbus_inmem/setup.py
  plugins/backbones/threatbus_rabbitmq/setup.py
  setup.py
Labels: maintenance :scissors:

#137 Release `suricata-threatbus` Docker image together with Threat Bus
  .github/workflows/python-egg.yml
  apps/suricata/CHANGELOG.md
  apps/suricata/Dockerfile
Labels: enhancement :sparkles:

#133 Introduce Dynaconf
  CHANGELOG.md
  Makefile
  README.md
  apps/stix-shifter/CHANGELOG.md
  apps/stix-shifter/README.md
  apps/stix-shifter/setup.py
  apps/stix-shifter/stix_shifter_threatbus/shifter.py
  apps/suricata/CHANGELOG.md
  apps/suricata/README.md
  apps/suricata/setup.py
  apps/suricata/suricata_threatbus/suricata.py
  apps/vast/CHANGELOG.md
  apps/vast/README.md
  apps/vast/pyvast_threatbus/pyvast_threatbus.py
  apps/vast/setup.py
  apps/zmq-app-template/README.md
  apps/zmq-app-template/setup.py
  apps/zmq-app-template/zmq_app_template/template.py
  benchmark/benchmark_config.yaml
  plugins/apps/threatbus_cif3/threatbus_cif3/plugin.py
  plugins/apps/threatbus_misp/threatbus_misp/plugin.py
  plugins/apps/threatbus_zeek/threatbus_zeek/plugin.py
  plugins/apps/threatbus_zmq_app/threatbus_zmq_app/plugin.py
  plugins/backbones/file_benchmark/file_benchmark/plugin.py
  plugins/backbones/threatbus_inmem/threatbus_inmem/plugin.py
  plugins/backbones/threatbus_rabbitmq/threatbus_rabbitmq/plugin.py
  plugins/backbones/threatbus_rabbitmq/threatbus_rabbitmq/rabbitmq_consumer.py
  requirements.txt
  setup.py
  systemd/pyvast-threatbus.service
  systemd/threatbus.service
  tests/integration/test_misp_inmem.py
  tests/integration/test_rabbitmq.py
  tests/integration/test_zeek_app.py
  tests/integration/test_zeek_inmem.py
  tests/integration/test_zmq_app_management.py
  tests/integration/test_zmq_app_message_roundtrips.py
  tests/utils/misp-ioc-sender/misp-ioc-sender.py
  tests/utils/misp-ioc-sender/requirements.txt
  threatbus/appspecs.py
  threatbus/backbonespecs.py
  threatbus/logger.py
  threatbus/threatbus.py
Labels: enhancement :sparkles:

#138 Remove Docker entrypoints
  CHANGELOG.md
  Dockerfile
  README.md
  apps/stix-shifter/Dockerfile
  apps/suricata/Dockerfile
  apps/vast/Dockerfile
Labels: maintenance :scissors:

#139 Fix env prefix for suricata app
  apps/suricata/suricata_threatbus/suricata.py
Labels: bug :beetle:

#141 Use latest Threat Bus sources in all ZMQ app's Dockerfiles
  .github/workflows/python-egg.yml
  .github/workflows/style-check.yml
  Dockerfile_pyvast_threatbus
  Dockerfile_stix_shifter_threatbus
  Dockerfile_suricata_threatbus
  apps/stix-shifter/CHANGELOG.md
  apps/suricata/CHANGELOG.md
  apps/vast/CHANGELOG.md
Labels: enhancement :sparkles:

#142 Minor fixups
  Makefile
  apps/stix-shifter/stix_shifter_threatbus/shifter.py
  apps/suricata/suricata_threatbus/suricata.py
  apps/vast/pyvast_threatbus/pyvast_threatbus.py
  apps/zmq-app-template/zmq_app_template/template.py
  requirements.txt
  setup.py
Labels: maintenance :scissors:

#143 Fix off-by-one error
  apps/stix-shifter/stix_shifter_threatbus/shifter.py
  apps/suricata/suricata_threatbus/suricata.py
  apps/vast/pyvast_threatbus/pyvast_threatbus.py
  apps/zmq-app-template/zmq_app_template/template.py
Labels: bug :beetle:

#144 Use FQDN in pyvast-threatbus metrics
  apps/vast/CHANGELOG.md
  apps/vast/pyvast_threatbus/pyvast_threatbus.py
Labels: enhancement :sparkles:

#145 Start measurement of query time metric w/ actual query
  apps/vast/CHANGELOG.md
  apps/vast/pyvast_threatbus/pyvast_threatbus.py
Labels: maintenance :scissors:
