Repository tenzir/threatbus, pull requests merged in 2021-08, with the labels that each got.

#158 Upload tenzir/threatbus:${sha} to Docker Hub
  .github/workflows/python-egg.yml
Labels: enhancement :sparkles:

#156 Add support for VAST live matching to threatbus
  CHANGELOG.md
  apps/vast/CHANGELOG.md
  apps/vast/pyvast_threatbus/message_mapping.py
  apps/vast/pyvast_threatbus/pyvast_threatbus.py
  apps/vast/pyvast_threatbus/test_message_mapping.py
Labels: enhancement :sparkles:, maintenance :scissors:

#159 Rename PyVAST Threat Bus to VAST Threat Bus
  .github/workflows/python-egg.yml
  README.md
  apps/vast/CHANGELOG.md
  apps/vast/README.md
  apps/vast/config.yaml.example
  apps/vast/setup.py
  apps/vast/vast_threatbus/__init__.py
  apps/vast/vast_threatbus/message_mapping.py
  apps/vast/vast_threatbus/metrics.py
  apps/vast/vast_threatbus/test_message_mapping.py
  apps/vast/vast_threatbus/test_metrics.py
  apps/vast/vast_threatbus/vast_threatbus.py
  docker/vast-threatbus/Dockerfile
  plugins/apps/threatbus_zmq/README.md
  systemd/README.md
  systemd/vast-threatbus.service
Labels: enhancement :sparkles:

#160 Rename the last instance of PYVAST_THREATBUS -> VAST_THREATBUS
  tests/utils/misp-ioc-sender/misp-ioc-sender.py
Labels: bug :beetle:
