Repository tenzir/threatbus, pull requests merged in 2021-11, with the labels that each got.

#171 Use low-priority exports if available
  CHANGELOG.md
  apps/vast/vast_threatbus/vast_threatbus.py
Labels: feature :gift:

#172 Prepare repository for 2021.11.18 release
  CHANGELOG.md
  apps/stix-shifter/CHANGELOG.md
  apps/stix-shifter/setup.py
  apps/suricata/CHANGELOG.md
  apps/suricata/setup.py
  apps/vast/setup.py
  apps/zmq-app-template/setup.py
  docker/vast-threatbus/Dockerfile
  plugins/apps/threatbus_cif3/setup.py
  plugins/apps/threatbus_misp/setup.py
  plugins/apps/threatbus_zeek/setup.py
  plugins/apps/threatbus_zmq/setup.py
  plugins/backbones/file_benchmark/setup.py
  plugins/backbones/threatbus_inmem/setup.py
  plugins/backbones/threatbus_rabbitmq/setup.py
  setup.py
Labels: maintenance :scissors:

#173 Fix check for `--low-priority` flag
  CHANGELOG.md
  apps/stix-shifter/CHANGELOG.md
  apps/stix-shifter/setup.py
  apps/suricata/CHANGELOG.md
  apps/suricata/setup.py
  apps/vast/CHANGELOG.md
  apps/vast/setup.py
  apps/vast/vast_threatbus/vast_threatbus.py
  apps/zmq-app-template/setup.py
  plugins/apps/threatbus_cif3/setup.py
  plugins/apps/threatbus_misp/setup.py
  plugins/apps/threatbus_zeek/setup.py
  plugins/apps/threatbus_zmq/setup.py
  plugins/backbones/file_benchmark/setup.py
  plugins/backbones/threatbus_inmem/setup.py
  plugins/backbones/threatbus_rabbitmq/setup.py
  setup.py
Labels: bug :beetle:

#175 Make Threat Bus independent of pluggy versions
  requirements.txt
  setup.py
  threatbus/threatbus.py
Labels: enhancement :sparkles:
