Repository tenzir/threatbus, pull requests merged in 2021-05, with the labels that each got.

#119 Print help text when starting without a config file
  CHANGELOG.md
  apps/vast/CHANGELOG.md
  apps/vast/pyvast_threatbus/pyvast_threatbus.py
  threatbus/threatbus.py
Labels: enhancement :sparkles:

#120 Subscribe multiple topics with a single subscription
  CHANGELOG.md
  plugins/apps/threatbus_zmq_app/threatbus_zmq_app/message_mapping.py
  plugins/apps/threatbus_zmq_app/threatbus_zmq_app/plugin.py
  tests/utils/zmq_receiver.py
  threatbus/data.py
Labels: feature :gift:

#118 Forward indicators to STIX-Shifter
  CHANGELOG.md
  Makefile
  apps/stix-shifter/CHANGELOG.md
  apps/stix-shifter/Makefile
  apps/stix-shifter/README.md
  apps/stix-shifter/config.yaml.example
  apps/stix-shifter/setup.py
  apps/stix-shifter/stix_shifter_threatbus/__init__.py
  apps/stix-shifter/stix_shifter_threatbus/shifter.py
  apps/vast/CHANGELOG.md
  apps/vast/pyvast_threatbus/pyvast_threatbus.py
  apps/zmq-app-template/Makefile
  apps/zmq-app-template/README.md
  apps/zmq-app-template/config.yaml.example
  apps/zmq-app-template/setup.py
  apps/zmq-app-template/zmq_app_template/__init__.py
  apps/zmq-app-template/zmq_app_template/template.py
Labels: feature :gift:

#121 Prepare May Release
  CHANGELOG.md
  apps/stix-shifter/CHANGELOG.md
  apps/stix-shifter/setup.py
  apps/vast/CHANGELOG.md
  apps/vast/setup.py
  apps/zmq-app-template/setup.py
  plugins/apps/threatbus_cif3/setup.py
  plugins/apps/threatbus_misp/setup.py
  plugins/apps/threatbus_zeek/setup.py
  plugins/apps/threatbus_zmq_app/setup.py
  plugins/backbones/file_benchmark/setup.py
  plugins/backbones/threatbus_inmem/setup.py
  plugins/backbones/threatbus_rabbitmq/setup.py
  setup.py
Labels: maintenance :scissors:

#123 Change chat from Gitter to Slack
  CHANGELOG.md
  README.md
Labels: maintenance :scissors:
