Repository tenzir/threatbus, pull requests merged in 2021-07, with the labels that each got.

#152 Pin version 2.x of stix2 package
  apps/stix-shifter/setup.py
  apps/suricata/setup.py
  apps/vast/setup.py
  apps/zmq-app-template/setup.py
  plugins/apps/threatbus_cif3/setup.py
  plugins/apps/threatbus_misp/setup.py
  plugins/apps/threatbus_zeek/setup.py
  plugins/apps/threatbus_zmq_app/setup.py
  plugins/backbones/file_benchmark/setup.py
  plugins/backbones/threatbus_inmem/setup.py
  plugins/backbones/threatbus_rabbitmq/setup.py
  requirements.txt
  setup.py
Labels: bug :beetle:

#153 Consolidate Docker files in dedicated directory
  .github/workflows/python-egg.yml
  docker/pyvast-threatbus/Dockerfile
  docker/stix-shifter-threatbus/Dockerfile
  docker/suricata-threatbus/Dockerfile
Labels: maintenance :scissors:

#150 Allow omitting more config values
  CHANGELOG.md
  README.md
  apps/stix-shifter/Makefile
  apps/suricata/Makefile
  apps/suricata/config.yaml.example
  apps/suricata/suricata_threatbus/suricata.py
  apps/vast/Makefile
  apps/vast/config.yaml.example
  apps/vast/pyvast_threatbus/pyvast_threatbus.py
  apps/zmq-app-template/Makefile
  config.yaml.example
  plugins/apps/threatbus_cif3/threatbus_cif3/plugin.py
  plugins/apps/threatbus_misp/threatbus_misp/plugin.py
  plugins/apps/threatbus_zeek/threatbus_zeek/plugin.py
  plugins/backbones/threatbus_rabbitmq/threatbus_rabbitmq/plugin.py
  threatbus/threatbus.py
Labels: enhancement :sparkles:

#151 Document that threatbus requires at least python3.7
  README.md
Labels: enhancement :sparkles:
