Repository tenzir/threatbus, pull requests merged in 2021-04, with the labels that each got.

#109 Handle VAST matcher CLI changes in pyvast-threatbus
  apps/vast/CHANGELOG.md
  apps/vast/pyvast_threatbus/message_mapping.py
  apps/vast/pyvast_threatbus/pyvast_threatbus.py
  apps/vast/pyvast_threatbus/test_message_mapping.py
Labels: bug :beetle:, maintenance :scissors:

#111 Update README with OpenCTI integration
  README.md
Labels: maintenance :scissors:

#110 Add timeout option for retro-queries
  apps/vast/CHANGELOG.md
  apps/vast/config.yaml.example
  apps/vast/pyvast_threatbus/message_mapping.py
  apps/vast/pyvast_threatbus/pyvast_threatbus.py
  apps/vast/pyvast_threatbus/test_message_mapping.py
Labels: enhancement :sparkles:

#112 Fix sighting context post-processing
  apps/vast/CHANGELOG.md
  apps/vast/pyvast_threatbus/message_mapping.py
  apps/vast/pyvast_threatbus/pyvast_threatbus.py
  threatbus/data.py
Labels: bug :beetle:

#113 Update chat URL in README
  CHANGELOG.md
  README.md
Labels: maintenance :scissors:

#114 Fix spelling of changelog categories
  CHANGELOG.md
  apps/vast/CHANGELOG.md
Labels: bug :beetle:

#115 Prepare April Release
  CHANGELOG.md
  README.md
  apps/vast/CHANGELOG.md
  apps/vast/setup.py
  plugins/apps/threatbus_cif3/setup.py
  plugins/apps/threatbus_misp/setup.py
  plugins/apps/threatbus_zeek/setup.py
  plugins/apps/threatbus_zmq_app/setup.py
  plugins/backbones/file_benchmark/setup.py
  plugins/backbones/threatbus_inmem/setup.py
  plugins/backbones/threatbus_rabbitmq/setup.py
  setup.py
Labels: maintenance :scissors:

#116 Fix bug in SnapshotRequest handling
  CHANGELOG.md
  plugins/apps/threatbus_zmq_app/threatbus_zmq_app/plugin.py
Labels: bug :beetle:
