Repository tenzir/threatbus, pull requests merged in 2022-01, with the labels that each got.

#183 shell.nix: Set correct editable sources names
  shell.nix
Labels: bug :beetle:

#186 Check for return code when running transform process
  apps/vast/vast_threatbus/vast_threatbus.py
Labels: bug

#187 Prepare Threat Bus and apps for 2022.01.27 release
  CHANGELOG.md
  apps/stix-shifter/CHANGELOG.md
  apps/stix-shifter/setup.py
  apps/suricata/CHANGELOG.md
  apps/suricata/setup.py
  apps/vast/CHANGELOG.md
  apps/vast/setup.py
  apps/zmq-app-template/setup.py
  docker/vast-threatbus/Dockerfile
  plugins/apps/threatbus_cif3/setup.py
  plugins/apps/threatbus_misp/setup.py
  plugins/apps/threatbus_zeek/setup.py
  plugins/apps/threatbus_zmq/setup.py
  plugins/backbones/file_benchmark/setup.py
  plugins/backbones/threatbus_inmem/setup.py
  plugins/backbones/threatbus_rabbitmq/setup.py
  setup.py
Labels: maintenance
